# Python Libraries

## Numpy 
NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

## What is an array
An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type



In [1]:
## importing the numpy

import numpy as np

In [2]:
my_list = [1,2,3,4,5]
arr=np.array(my_list)

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
arr.shape ##shape is used to find number of rows and columns

(5,)

In [6]:
## Multinested array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[7,8,5,9,3]

arr = np.array([my_lst1,my_lst2,my_lst3])

In [7]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [7, 8, 5, 9, 3]])

In [49]:
## Accessing the array element

arr= np.array([1,2,3,4,5,6,7,8,9])

In [48]:
arr[3]

In [8]:
arr[1:3]

array([[2, 3, 4, 5, 6],
       [7, 8, 5, 9, 3]])

In [9]:
arr[1:4]

array([[2, 3, 4, 5, 6],
       [7, 8, 5, 9, 3]])

In [10]:
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [11]:
arr[0:3]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [7, 8, 5, 9, 3]])

In [12]:
arr[1:,3:]

array([[5, 6],
       [9, 3]])

In [20]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.linspace(1,10) ##using in DeepLearning

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

## Copy() function and broadcasing

In [25]:
arr[3:]=100
arr

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [24]:
arr[3:]=500
arr

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [13]:
arr.shape

(3, 5)

In [14]:
arr.reshape(5,3) ##we can change the shape

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 7, 8],
       [5, 9, 3]])

In [32]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [28]:
### some conditions very useful in EDA

arr*2

array([  0,   2,   4, 200, 200, 200, 200, 200, 200, 200])

In [30]:
arr/2

array([ 0. ,  0.5,  1. , 50. , 50. , 50. , 50. , 50. , 50. , 50. ])

In [31]:
arr<2

array([ True,  True, False, False, False, False, False, False, False,
       False])

In [33]:
np.ones(2)

array([1., 1.])

In [42]:
np.ones((5),dtype=int)

array([1, 1, 1, 1, 1])

In [45]:
##random disibution
np.random.rand(3,3) #it wil be giving 0 to 1

array([[0.01798311, 0.30991193, 0.96498311],
       [0.24894062, 0.93069258, 0.31147549],
       [0.77209805, 0.2021558 , 0.40379157]])

In [47]:
arr_ex=np.random.randn(4,4)
arr_ex

array([[-1.13861364, -2.21138542, -1.30167183,  0.36557597],
       [ 0.1601062 ,  0.95318983,  0.84775901, -1.09185868],
       [ 1.31870442, -0.0243951 , -1.11851276, -0.37715544],
       [ 0.98097503,  0.40242639,  1.45832412, -0.02108984]])

### .loc[] and .iloc[]
In Pandas, .loc[] and .iloc[] are used to select rows and columns from a DataFrame, but they work differently:

In [15]:
import pandas as pd

data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35]}

df = pd.DataFrame(data, index=['a', 'b', 'c'])

# Get row with label 'b'
print(df.loc['b'])

# Get 'Age' column of rows 'a' to 'b'
print(df.loc['a':'b', 'Age'])



Name    Bob
Age      30
Name: b, dtype: object
a    25
b    30
Name: Age, dtype: int64


## Indexing

4